project:
  type: website
  execute-dir: file

lang: es
date-format: "[Xalapa, Ver.,] D [de] MMMM, YYYY"

website:
  title: "Ciencia Abierta"
  favicon: pluma-escritura.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/equihuam/ciencia-reproducible
      - icon: x
        href: https://x.com/
      - icon: instagram
        href: https://www.instagram.com/ 
format:
  html:
    theme: cosmo
    css: styles.css
  pdf: 
    toc: false
    number-sections: false
    colorlinks: true
    papersize: letter

execute: 
  freeze: true
  
